import SPECIES_CITATION from './SPECIES_CITATION'
import SPECIES_COUNTRIES from './SPECIES_COUNTRIES'
import SPECIES_FETCH from './SPECIES_FETCH'
import SPECIES_HISTORICAL from './SPECIES_HISTORICAL'
import SPECIES_NARRATIVE from './SPECIES_NARRATIVE'
import SPECIES_THREATS from './SPECIES_THREATS'

const Reducers = Object.assign(
  {},
  SPECIES_CITATION,
  SPECIES_COUNTRIES,
  SPECIES_FETCH,
  SPECIES_HISTORICAL,
  SPECIES_NARRATIVE,
  SPECIES_THREATS
)

export default Reducers
